import pptxgen from "pptxgenjs";

export async function generateReportPPT(dateRange: string) {
  // Create a new Presentation
  let pres = new pptxgen();

  // Set Presentation metadata
  pres.author = "SyncFlow";
  pres.company = "SyncFlow Analytics";
  pres.subject = "Social Media Analytics Report";
  pres.title = "SyncFlow Report";
  pres.layout = "LAYOUT_16x9";

  // Define Master Slide for consistent header/footer
  pres.defineSlideMaster({
    title: "MASTER_SLIDE",
    background: { color: "FFFFFF" },
    objects: [
      // Top Color Bar
      { rect: { x: 0, y: 0, w: "100%", h: 0.1, fill: { color: "6366F1" } } },
      // Footer Line
      { line: { x: 0.5, y: 6.8, w: 9.0, h: 0, line: { color: "E2E8F0", width: 1 } } },
      // Footer Text
      { text: { text: "Generated by SyncFlow Analytics", options: { x: 0.5, y: 6.9, w: 4, h: 0.3, fontSize: 10, color: "94A3B8" } } },
      { text: { text: "CONFIDENTIAL", options: { x: 7.5, y: 6.9, w: 2, h: 0.3, align: "right", fontSize: 10, color: "94A3B8" } } }
    ]
  });

  // ---------------------------------------------------------
  // SLIDE 1: Title Slide
  // ---------------------------------------------------------
  let slide1 = pres.addSlide({ masterName: "MASTER_SLIDE" });
  
  // Title
  slide1.addText("SyncFlow", { x: 0.5, y: 1.5, w: 4, h: 0.5, fontSize: 24, bold: true, color: "1E293B" });
  slide1.addText("Social Media Analytics", { x: 0.5, y: 2.2, w: 8, h: 1, fontSize: 44, bold: true, color: "0F172A" });
  slide1.addText("Comprehensive Performance Report", { x: 0.5, y: 3.2, w: 8, h: 0.5, fontSize: 20, color: "64748B" });
  
  // Date Block
  slide1.addText("GENERATED ON", { x: 0.5, y: 4.5, w: 3, h: 0.3, fontSize: 10, bold: true, color: "94A3B8" });
  slide1.addText(new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }), 
    { x: 0.5, y: 4.8, w: 4, h: 0.4, fontSize: 16, bold: true, color: "1E293B" });

  // ---------------------------------------------------------
  // SLIDE 2: Executive Summary
  // ---------------------------------------------------------
  let slide2 = pres.addSlide({ masterName: "MASTER_SLIDE" });
  
  slide2.addText("EXECUTIVE SUMMARY", { x: 0.5, y: 0.5, w: 4, h: 0.4, fontSize: 12, bold: true, color: "4F46E5" });
  slide2.addText(dateRange, { x: 7.5, y: 0.5, w: 2, h: 0.4, align: "right", fontSize: 12, color: "64748B" });

  // Metric 1: Audience
  slide2.addShape(pres.ShapeType.rect, { x: 0.5, y: 1.5, w: 2.8, h: 1.5, fill: { color: "F8FAFC" }, line: { color: "E2E8F0" }, rectRadius: 0.1 });
  slide2.addText("Total Audience", { x: 0.7, y: 1.7, w: 2.4, h: 0.3, fontSize: 14, bold: true, color: "475569" });
  slide2.addText("1,245.8K", { x: 0.7, y: 2.1, w: 2.4, h: 0.5, fontSize: 28, bold: true, color: "0F172A" });
  slide2.addText("+12.4% this month", { x: 0.7, y: 2.6, w: 2.4, h: 0.3, fontSize: 11, bold: true, color: "10B981" });

  // Metric 2: Engagement
  slide2.addShape(pres.ShapeType.rect, { x: 3.6, y: 1.5, w: 2.8, h: 1.5, fill: { color: "F8FAFC" }, line: { color: "E2E8F0" }, rectRadius: 0.1 });
  slide2.addText("Engagement", { x: 3.8, y: 1.7, w: 2.4, h: 0.3, fontSize: 14, bold: true, color: "475569" });
  slide2.addText("482.3K", { x: 3.8, y: 2.1, w: 2.4, h: 0.5, fontSize: 28, bold: true, color: "0F172A" });
  slide2.addText("+8.1% this month", { x: 3.8, y: 2.6, w: 2.4, h: 0.3, fontSize: 11, bold: true, color: "10B981" });

  // Metric 3: Impressions
  slide2.addShape(pres.ShapeType.rect, { x: 6.7, y: 1.5, w: 2.8, h: 1.5, fill: { color: "F8FAFC" }, line: { color: "E2E8F0" }, rectRadius: 0.1 });
  slide2.addText("Impressions", { x: 6.9, y: 1.7, w: 2.4, h: 0.3, fontSize: 14, bold: true, color: "475569" });
  slide2.addText("3.2M", { x: 6.9, y: 2.1, w: 2.4, h: 0.5, fontSize: 28, bold: true, color: "0F172A" });
  slide2.addText("+24.5% this month", { x: 6.9, y: 2.6, w: 2.4, h: 0.3, fontSize: 11, bold: true, color: "10B981" });

  // Chart Data
  let arrDataRegions = [
    {
      name: "Audience Growth",
      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
      values: [200, 350, 400, 600, 750, 800, 1245]
    }
  ];
  
  slide2.addChart(pres.ChartType.bar, arrDataRegions, { 
    x: 0.5, y: 3.5, w: 9.0, h: 3.0, 
    barDir: "col",
    showTitle: true,
    title: "Growth Trajectory (Last 7 Months)",
    titleFontSize: 12,
    titleColor: "475569",
    chartColors: ["4F46E5"]
  });

  // ---------------------------------------------------------
  // SLIDE 3: Network Breakdown
  // ---------------------------------------------------------
  let slide3 = pres.addSlide({ masterName: "MASTER_SLIDE" });
  
  slide3.addText("NETWORK BREAKDOWN", { x: 0.5, y: 0.5, w: 4, h: 0.4, fontSize: 12, bold: true, color: "4F46E5" });

  let rows = [
    [
      { text: "Network", options: { bold: true, color: "64748B", fill: "F8FAFC" } },
      { text: "Followers", options: { bold: true, color: "64748B", fill: "F8FAFC" } },
      { text: "Posts", options: { bold: true, color: "64748B", fill: "F8FAFC" } },
      { text: "Engagement Rate", options: { bold: true, color: "64748B", fill: "F8FAFC" } }
    ],
    ["Instagram", "452.1K", "124", "4.2%"],
    ["LinkedIn", "182.9K", "42", "8.9%"],
    ["Twitter", "610.8K", "450", "1.8%"]
  ];

  slide3.addTable(rows as any, { 
    x: 0.5, y: 1.5, w: 9.0, 
    rowH: 0.6,
    fill: "FFFFFF",
    color: "333333",
    fontSize: 14,
    valign: "middle",
    border: { type: "solid", color: "E2E8F0", pt: 1 }
  });

  // Generate and save the file
  pres.writeFile({ fileName: `SyncFlow_Report_${formatDate(new Date())}.pptx` });
}

function formatDate(date: Date) {
  return date.toISOString().split('T')[0];
}
